### ISSUE TITLE
Interloper variables

### ISSUE THREAD

**Issue by DCunnama** [pelahi/VELOCIraptor-STF#3]
io.cxx: In function ‘void WriteProperties(Options&, Int_t, PropData*)’:
io.cxx:1261: error: ‘struct PropData’ has no member named ‘n_interloper’
io.cxx:1265: error: ‘struct PropData’ has no member named ‘M_interloper’

It appears the latest change introduced a bug.

If ZOOMSIM is not defined, HIGHRES is not defined, however that doesn't stop io.cxx from attemping to access the interloper members.

Not sure what the desired behaviour is.

**Comment by pelahi** [comment]
For checking contamination will fix flag

On 20 Jan 2017 17:55, "DCunnama" <notifications@github.com> wrote:

io.cxx: In function ‘void WriteProperties(Options&, Int_t, PropData*)’:
io.cxx:1261: error: ‘struct PropData’ has no member named ‘n_interloper’
io.cxx:1265: error: ‘struct PropData’ has no member named ‘M_interloper’

It appears the latest change introduced a bug.

If ZOOMSIM is not defined, HIGHRES is not defined, however that doesn't
stop io.cxx from attemping to access the interloper members.

Not sure what the desired behaviour is.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pelahi/VELOCIraptor-STF/issues/3>, or mute the thread

**Comment by pelahi** [comment]
should be fixed, as I'm running it now with latest version.

**Comment by DCunnama** [comment]
Not for me, have you tried to compile with ZOOMSIM off?

**Comment by pelahi** [comment]
arg, yes, didn't push to repository before I left for soccer. Sorry Dan.

**Comment by DCunnama** [comment]
Ha ha, ok fair enough. No problem. Enjoy the football!
